functional:
  - Пользователи должны иметь возможность создавать лобби с друзьями или другими игроками
  - Пароль к учётной записи должен содержать хотя бы один специальный символ
  - Каждый игрок должен иметь возможность проверки своего решения колличество проверок должно быть неограничено
  - Победитель должен иметь возможность покинуть лобби после выполнения задания
  - Игра должна продолжаться пока оба игрока не покинут лобби дав возможность проигравшему завершить задание
  - Пользователи должны иметь возможность переподключаться к лобби в случае отключения от игры
  - Пользователи должны иметь возможность подключаться к игровому лобби друг друга
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность входить в систему с использованием учетных данных
  - Пользователь должен иметь возможность создавать новую игру
  - Должны быть опции настройки (например, уровень сложности)
  - Игроки должны получать очки за выполнение задач
  - Должна быть таблица лидеров для отслеживания результатов игроков
  - Игроки должны иметь возможность общаться друг с другом в чате во время игры
  - Игра должна быть доступна на веб-браузерах (Chrome, Firefox, Safari, Edge)
  - Интерфейс должен быть удобным для использования на различных устройствах (ПК, планшеты, мобильные телефоны)
  - Игра должна поддерживать несколько языков программирования
  - Должна быть опция выбора конкретной задачи или автоматическая подборка задачи наугад
  - Оба игрока должны видеть друг у друга редактор кода и вывод тестов
  - Задачи в играх должны быть даны на двух языках — русском и английском
  - Должна быть возможность наблюдения за ходом игры другими пользователями
  - В каждой игре должен быть установлен таймер, отсчитывающий время на выполнение задач
  - Игроки должны иметь возможность видеть текущее состояние игры (например, оставшееся время)
  - Завершенные игры должны быть доступны в записи для просмотра
  - Пользователь должен иметь возможность создавать турниры
  - Пользователь должен иметь возможность создавать кастомные задачи
  - Пользователь должен иметь возможность создавать наборы задач
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Должна быть доступна документация для пользователей (например, правила игры)
  - Сайт должен корректно обрабатывать все запросы клиента
implicit:
  - Игроки должны иметь доступ к своей статистике игр (количество сыгранных игр, среднее время выполнения задач, количество побед и поражений)
  - Возможность для игроков оставлять отзывы о задачах и об игре в целом
